### ISSUE TITLE
疑惑请教

### ISSUE THREAD

**Issue by topDreamer** [zifengcheng/SLMM#1]
您好！感谢非常好出色的工作！粗读论文有以下疑惑，麻烦请指教：
1、请问在构建 open class 这一类（K+1）的过程中，在Code中为什么要构建一个3类的分类器（self.classifier_2 = nn.Linear(768,3) ）https://github.com/zifengcheng/SLMM/blob/a2623fcaeb4a07a6d2d941efc450c3b15164a6ef/model.py#L13

2、从论文中的Ablation Study中可以观察到 Manifold Mixup 的作用并不是太显著，请问实验中是否尝试过[1]中的 mixup 的做法？
[1]Out-of-Scope Intent Detection with Self-Supervision and Discriminative Training

**Comment by zifengcheng** [comment]
1. 我在实验的时候发现这样效果会稍微好一点(具体我记不清了，应该差不多1个点吧，你可以跑下试试)。可以理解为虽然开放类是一个类，但是实际中可能是多个类，比如开放类是天气，体育和音乐。所以我统一安排了3个类，给开放类分配了3个区域，用最大的logits当做开放类的logits。可能在不同的数据集不同的值更好，但是我也没有调了。
2. 我们生成样本的方式应该和[1]是类似的，都是利用2个意图不同的样本生成开放类样本，不过具体的实现方式不同。我没有尝试过他们的实现方法。

**Comment by topDreamer** [comment]
理解了，非常感谢！
